### ISSUE TITLE
Le parse avec Kimono ne marche plus

### ISSUE THREAD

**Issue by Bigood** [maximelebreton/SpotiFIP#1]
On a une erreur dans la console :

> Failed to load resource: the server responded with a status of 410 (Gone)

Je pense que ton API sur Kimonolabs n'est plus à jour ; si tu veux bien que je la corrige, donne moi un accès (si on peut).

PS : J'aime beaucoup l'idée de ton app, je pense en faire une version mobile à l'occasion, avec ton accord!

**Comment by maximelebreton** [comment]
merci @Bigood pour le signalement, effectivement KimonoLabs a effectué des modifications dans son api, je viens de tout mettre à jour , et ça refonctionne !

d'ailleurs, pour le moment l'api est liée à mon compte, mais je préférerais qu'elle puisse être accessible à tous ceux qui le souhaitent, le problème est que KimonoLabs ne propose pas de moyen pour partager une api entre plusieurs collaborateurs, donc à moins de créer un compte spécifique, pour l'instant je ne vois pas d'autre solution pour avoir accès partagé à cette api. Qu'en dis tu ?

Et pour la version mobile, je pense qu'il y'a une bonne base avec le code actuel, mais le problème est que l'embed player de Spotify n'est pas compatible mobile.
La solution pourrait consister à mettre en place un player mobile qui fait appel à l'api de Spotify, mais dans ce cas Spotify limite l'écoute à 30 secondes...
Bref, à réfléchir donc.

En tout cas n'hésite pas à apporter des modifications, c'est dispo sur github pour ça !

**Comment by Bigood** [comment]
Pour Kimonolabs, je viens de leur demander, pas de soucis pour créer un compte commun avec un yopmail par exemple, en attendant qu'ils implémentent le compte groupé / libre.

Pour la version mobile, à voir plus tard...

Merci pour le correctif en tout cas. Si j'ai, ou tu as des idées d'améliorations, je contribuerai avec plaisir :)
